### ISSUE TITLE
Flash positive result for all 

### ISSUE THREAD

**Issue by ehsandeep** [gwen001/3rdparty-services#1]
as listed in readme :     **php 3rdparty.php -d yahoo -s zendesk** am assuming -d is for domain name i.e yahoo.com , if not from where its taking domain value for the subdomain test ?
and i can see same result for all like  **php 3rdparty.php -d lol -s zendesk**

**Comment by gwen001** [comment]
Hi,

This script tests if a specific name has been claimed on a third party service like Heroku, Zendesk and so on. For that, it curls the 3rd party service itself and performs some little checks like headers return or regexp the content...

`php 3rdparty.php -d yahoo -s zendesk`

This will call http://yahoo.zendesk.com and check the headers, then the script calls Zendesk API and checks json returns.

If you think the script is wrong then manual check the url by yourself and show me the result, I would fix it.
Also feel free to change the code or add new providers.

**Comment by ehsandeep** [comment]
Thanks for the reply, got cleared my doubts now.

please do close the issue .
